spring:
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  security:
    jwt:
      secret-key: myclave
      time: 15000
      refresh-time: 15000
  application:
    name: ms_listas_app

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_flutter_demos?useUnicode=true&characterEncoding=utf-8
    password: sa
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  # address: 192.168.1.36
  port: 5500
