application:
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      # 1h in hours
      expiration-time: 8
      refresh-time: 15000

spring:
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: ms_listas_app

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/school_db?useUnicode=true&characterEncoding=utf-8
    password: sa
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  # address: 192.168.1.36
  port: 5500
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/
    instance:
      preferIpAddress: true #